preproc debugging and added QA reporting.

diff --git a/bin/ica-aroma b/bin/ica-aroma
--- a/bin/ica-aroma
+++ b/bin/ica-aroma
@@ -4,7 +4,7 @@ err () {
   if [[ -n $log ]]; then
     echo "ERROR: $1" >> $log
   else
-    echo "ERROR: $1" > &2
+    echo "ERROR: $1" >&2
   fi
   cleanup 1
 }
@@ -84,7 +84,7 @@ for i in {0..4}; do
   if [[ -z ${vars[i]} ]]; then
     err "${varnames[i]} argument not provided."
   fi
-  if [[ ${vars[i]} != outdir && ${vars[i]} != log && ! -f ${vars[i]} ]]; then
+  if [[ ${varnames[i]} != outdir && ${varnames[i]} != log && ! -f ${vars[i]} ]]; then
     err "${varnames[i]} does not exist."
   fi
 done
@@ -128,6 +128,11 @@ mask=$tmpdir/bet_mask.nii.gz
 
 # Run ICA-AROMA.
 echo "Running AROMA..." >> $log
+# Make paths absolute
+affmat=$(readlink -m $affmat)
+warp=$(readlink -m $warp)
+outdir=$(readlink -m $outdir)
+
 python ${AROMA_DIR}/ICA_AROMA.py -i $func -o $outdir -a $affmat -w $warp \
   -mc $mcf -m $mask -den no >> $log 2>&1
 command_check "ICA_AROMA.py"
diff --git a/bin/preproc b/bin/preproc
--- a/bin/preproc
+++ b/bin/preproc
@@ -17,9 +17,17 @@ warn () {
 
 num_check () {
   # checks if input is a number. neg or pos; int or float
+  local num=$1
+  local sign=$2
+  local name=$3
   local re='^-?([0-9]+)?[.]?[0-9]+$'
-  if ! [[ $1 =~ $re ]] ; then
-   err "$1 is not a number"
+  if ! [[ $num =~ $re ]] ; then
+   err "$name is not a number"
+  fi
+  if [[ $(echo "$num < 0" | bc -l) == 1 && $sign == "pos" ]]; then
+    err "$name is negative"
+  elif [[ $(echo "$num > 0" | bc -l) == 1 && $sign == "neg" ]]; then
+    err "$name is positive"
   fi
 }
 
@@ -156,8 +164,8 @@ elif [[ $1 == -h || $1 == --help ]]; then
   echo "                      FEAT processing, (2) anatomical registration, (3) ICA"
   echo "                      artifact classification, (4) denoising, (5) motion"
   echo "                      artifact detection, (6) surface mapping, dilating, and"
-  echo "                      smoothing (E.g. --stop 4)."
-  echo "  --restart <stage>   Restart processing from a specific stage (2-6)."
+  echo "                      smoothing, (7) making QA report (E.g. --stop 4)."
+  echo "  --restart <stage>   Restart processing from a specific stage (2-7)."
   echo "  --log <file>        Specify the logfile."
   echo
   exit
@@ -173,7 +181,7 @@ fixmode=
 if [[ -z $FIX_DIR ]]; then
   fixW=
 else
-  fixW=$FIX_DIR/training_files/$FIX_RDATA
+  fixW=$FIX_RDATA
 fi
 fixT=10
 nuis_reg=
@@ -181,7 +189,7 @@ fdrms=1.5
 dvars=
 dil=0
 fwhm=2
-stpstage=6
+stpstage=7
 ststage=
 
 subj=
@@ -289,6 +297,9 @@ while [[ $1 == -* ]]; do
   esac
 done
 
+# Debug mode
+set -xv
+
 printf '%s\n%s\n' "Starting preproc job at $now (id=$id)." \
   "command line: $scriptname $args" | tee -a $log
 
@@ -300,8 +311,8 @@ trap "cleanup 1" SIGHUP SIGINT SIGTERM
 # if 1 positional, assume restarting preproc
 if [[ $# == 3 ]]; then
   subj=$1
-  input=$2
-  output=$3
+  input=$(readlink -m $2)
+  output=$(readlink -m $3)
   # in case someone adds .feat
   output=${output%.feat}
   featdir=${output}.feat
@@ -313,26 +324,28 @@ elif [[ $# == 1 ]]; then
     err "Incorrect arguments."
   fi
   intre='^-?[1-9][0-9]*$'
-  if [[ ! $ststage =~ $intre ]] || (( $ststage < 2 || $ststage > 6 )); then
-    err "Restart stage should be between 2-6."
+  if [[ ! $ststage =~ $intre ]] || (( $ststage < 2 || $ststage > 7 )); then
+    err "Restart stage should be between 2-7."
   fi
   featdir=${1%/}
   func=$featdir/filtered_func_data.nii.gz
   if [[ ! -f $func ]]; then
     err "Volume data $func doesn't exist. Can't restart."
   fi
+  nvols=`fslnvols $func`
+  tr=`fslinfo $func | grep "^pixdim4" | sed 's@pixdim4\s*@@'`
   cleanfunc=$featdir/filtered_func_data_clean.nii.gz
   if (( $ststage > 4 )) && [[ ! -f $cleanfunc ]]; then
     err "Clean volume data $cleanfunc doesn't exist. Must run denoising (stage 4)."
   fi
-  nvols=`fslnvols $func`
   oldcommand=$featdir/command.txt
   if [[ ! -f $oldcommand ]]; then
     err "Command file $featdir/command.txt doesn't exist. Can't restart."
   fi
-  # subject is first positional arg of three
+  # subject is first positional arg of three, input is second
   oldcommand=( `head -n 1 $oldcommand` )
-  subj=${oldcommand[-3]}
+  subj=${oldcommand[*]: -3:1}
+  input=${oldcommand[*]: -2:1}
 else
   err "Incorrect number of arguments $#."
 fi
@@ -352,12 +365,12 @@ if [[ ! -d $downsampdir ]]; then
 fi
 
 # check numerical options
-num_check $fdrms
+num_check $fdrms pos FDRMS
 if [[ -n $dvars ]]; then
-  num_check $dvars
+  num_check $dvars pos DVARS
 fi
-num_check $fwhm
-num_check $dil
+num_check $fwhm pos FWHM
+num_check $dil pos Dil
 
 # check slice timing option
 if [[ -n $slorder ]]; then
@@ -442,15 +455,8 @@ fi
 # Check band-pass filtering options
 int_check $hpf
 int_check $lpf
-dobptf=
-# Convert seconds to sigmas if > 0
-if (( $hpf >= 0 ));
-  hpf=$(echo "$hpf/(2.0 * $tr)" | bc -l)
-  dobptf=TRUE
-fi
-if (( $lpf >= 0 ));
-  lpf=$(echo "$lpf/(2.0 * $tr)" | bc -l)
-  dobptf=TRUE
+if (( $hpf <= $lpf )) && (( $hpf > 0 )); then
+  err "hpf can't be smaller than lpf."
 fi
 
 # Check nuisance regression option.
@@ -466,8 +472,8 @@ fi
 
 if [[ -n $stpstage ]]; then
   int_check $stpstage
-  if (( $stpstage < 1 || $stpstage > 6 )); then
-    err "Stop stage should be between 1-6."
+  if (( $stpstage < 1 || $stpstage > 7 )); then
+    err "Stop stage should be between 1-7."
   fi
   if (( $stpstage < $ststage )); then
     err "Stop stage should be >= restart stage."
@@ -501,11 +507,11 @@ if (( $ststage <= 1 )); then
   done
 
   # feat preparation
-  # fsf must contain absolute paths
+  # Note: fsf must contain absolute paths
   fsf=$tmpdir/design.fsf
   cp $PRPRC_TEMP $fsf
-  sed -i 's@\(set feat_files(1)\)\(.*\)@\1 "'`readlink -m $input`'"@' $fsf
-  sed -i 's@\(set fmri(outputdir)\)\(.*\)@\1 "'`readlink -m $output`'"@' $fsf
+  sed -i 's@\(set feat_files(1)\)\(.*\)@\1 "'$input'"@' $fsf
+  sed -i 's@\(set fmri(outputdir)\)\(.*\)@\1 "'$output'"@' $fsf
   tr=`fslinfo $input | grep "^pixdim4" | sed 's@pixdim4\s*@@'`
   sed -i 's@\(set fmri(tr)\)\(.*\)@\1 '$tr'@' $fsf
   sed -i 's@\(set fmri(npts)\)\(.*\)@\1 '$nvols'@' $fsf
@@ -557,8 +563,13 @@ if (( $ststage <= 2 )); then
   command_check "surface reg flirt init"
   bbregister --s $subj --mov $featdir/example_func_brain.nii.gz \
     --reg $featdir/surfreg/register.dat --init-reg $featdir/surfreg/flirt_init.dat \
-    --t2 --fslregout $featdir/surfreg/register.mat 2>&1 1>/dev/null | tee -a $log
+    --t2  2>&1 1>/dev/null | tee -a $log
   command_check "surface registration"
+  tkregister2 --s $subj --mov $featdir/example_func_brain.nii.gz --fstarg \
+    --reg $featdir/surfreg/register.dat \
+    --fslregout $featdir/surfreg/register.mat \
+    --noedit 2>&1 1>/dev/null | tee -a $log
+  command_check "registration conversion to FSL format."
   # Pull back white surface to functional space for QA.
   for hemi in lh rh; do
     mri_surf2vol --mkmask --hemi $hemi --projfrac 0.5 \
@@ -616,11 +627,11 @@ if (( $ststage <= 3 )); then
     command_check "anatomical registration conversion to FSL format"
     cp $featdir/example_func.nii.gz $featdir/reg/example_func.nii.gz
     # FIX feature extraction
-    ./${FIX_DIR}/fix -f $featdir 2>&1 1>/dev/null | tee -a $log
+    sh ${FIX_DIR}/fix -f $featdir 2>&1 1>/dev/null | tee -a $log
     command_check "FIX feature extraction"
     
     echo "(id=$id) FIX classification..." | tee -a $log
-    ./${FIX_DIR}/fix -c $featdir $fixW $fixT 2>&1 1>/dev/null | tee -a $log
+    sh ${FIX_DIR}/fix -c $featdir $fixW $fixT 2>&1 1>/dev/null | tee -a $log
     command_check "FIX classification"
   fi
 fi
@@ -639,7 +650,7 @@ if (( $ststage <= 4 )); then
   if [[ -n $dofixr ]]; then 
     echo "(id=$id) FIX artifact removal..." | tee -a $log
     fixWname=`basename ${fixW%.RData}`
-    ./${FIX_DIR}/fix -a $featdir/fix4melview_${fixWname}_thr${fixT}.txt 2>&1 1>/dev/null | tee -a $log
+    sh ${FIX_DIR}/fix -a $featdir/fix4melview_${fixWname}_thr${fixT}.txt 2>&1 1>/dev/null | tee -a $log
     command_check "FIX noise removal"
   fi
   
@@ -653,10 +664,26 @@ if (( $ststage <= 4 )); then
     command_check "ica-aroma filtering"
   fi
   
+  # Band-pass filtering
+  dobptf=
+  # Convert seconds to sigmas if > 0
+  if (( $hpf >= 0 )); then
+    hpf=$(echo "$hpf/(2.0 * $tr)" | bc -l)
+    dobptf=TRUE
+  fi
+  if (( $lpf >= 0 )); then
+    lpf=$(echo "$lpf/(2.0 * $tr)" | bc -l)
+    dobptf=TRUE
+  fi
   if [[ -n $dobptf ]]; then
     echo "(id=$id) Band-pass filtering..." | tee -a $log
-    echo "(id=$id) HPF sigma: $hpf; LPF sigma: $lpf." | tee -a $log
-    fslmaths $cleanfunc -bptf $hpf $lpf $cleanfunc 2>&1 1>/dev/null | tee -a $log
+    round_hpf=$(printf '%.2f' $hpf)
+    round_lpf=$(printf '%.2f' $lpf)
+    echo "(id=$id) HPF sigma: $round_hpf; LPF sigma: $round_lpf." | tee -a $log
+    # Temporal filtering removes mean. This is what feat does to get it back
+    fslmaths $cleanfunc -Tmean $tmpdir/tempmean.nii.gz
+    fslmaths $cleanfunc -bptf $hpf $lpf -add $tmpdir/tempmean.nii.gz \
+      $cleanfunc 2>&1 1>/dev/null | tee -a $log
     command_check "band-pass filtering"
   fi
 
@@ -681,36 +708,31 @@ if (( $ststage <= 4 )); then
     fslmaths $tmpdir/$region.lh.nii.gz -max $tmpdir/$region.rh.nii.gz \
       $featdir/art/$region.nii.gz 2>&1 1>/dev/null | tee -a $log
     # extract mean time series
-    fslmeants -i $func -m $featdir/art/$region.nii.gz \
+    fslmeants -i $cleanfunc -m $featdir/art/$region.nii.gz \
       -o $featdir/art/$region.values.txt
     # Make confound regressor by normalizing region signal.
     normalize $featdir/art/$region.values.txt $featdir/art/$region.confound.txt
   done
 
   # plot average time series for three regions.
-  fsl_tsplot -i $featdir/art/gm.values.txt,$featdir/art/wm.values.txt,$featdir/art/csf.values.txt \
-    --labels=grey.m,white.m,csf -o $featdir/art/gm-wm-csf.values.png \
-    -t "Average time-series across tissue types"
+  fsl_tsplot -i $featdir/art/gm.confound.txt,$featdir/art/wm.confound.txt,$featdir/art/csf.confound.txt \
+    --labels=grey.m,white.m,csf -o $featdir/art/gm-wm-csf.confound.png \
+    -t "Normalized average time-series across tissue types"
 
   # Generate linear trend nuisance covariate.
   make_lin_trend $nvols $featdir/art/lin.confound.txt
   # Regress out nuisance covariates if asked for.
   if [[ -n $nuis_reg ]]; then
     echo "(id=$id) Regressing nuisance covarariates $nuis_reg..." | tee -a $log
-    # First save a copy of the pre-filtered data (if it doesn't already exist).
-    noisyfunc=$featdir/filtered_func_data_noisy.nii.gz
-    if [[ ! -f $noisyfunc ]]; then
-      cp $func $noisyfunc
-    fi
 
     nuis_dm=$featdir/art/nuisance.dm.txt
-    rm $nuis_dm 2>/dev/null # Important if restarting
+    conf_list=
     for cov in $nuis_reg; do
-      paste $featdir/art/$cov.confound.txt $nuis_dm > $nuis_dm
+      conf_list="$conf_list $featdir/art/$cov.confound.txt"
     done
-    mv $func $tmpdir/prefilt.nii.gz
-    fsl_regfilt -i $tmpdir/prefilt.nii.gz -d $nuis_dm \
-      -o $func -m $featdir/mask.nii.gz 2>&1 1>/dev/null | tee -a $log
+    paste $conf_list > $nuis_dm
+    fsl_regfilt -i $cleanfunc -d $nuis_dm \
+      -o $cleanfunc -m $featdir/mask.nii.gz 2>&1 1>/dev/null | tee -a $log
     command_check "Nuisance regression"
   fi
 fi
@@ -797,21 +819,21 @@ if (( $ststage <= 5 )); then
     --ymin=$dvars_ymin --ymax=$dvars_ymax 2>&1 1>/dev/null | tee -a $log
 
   echo "(id=$id) Generating tSNR and tSD images..." | tee -a $log
-  fslmaths $cleanfunc -Tstd -mas $featdir/mask.nii.gz \
-    $featdir/art/filtered_func_clean_tSD.nii.gz 2>&1 1>/dev/null | tee -a $log
-  fslmaths $cleanfunc -Tmean -div $featdir/art/filtered_func_clean_tSD.nii.gz \
+  fslmaths $func -Tstd -mas $featdir/mask.nii.gz \
+    $featdir/art/filtered_func_tSD.nii.gz 2>&1 1>/dev/null | tee -a $log
+  fslmaths $func -Tmean -div $featdir/art/filtered_func_tSD.nii.gz \
     -mas $featdir/mask.nii.gz \
-    $featdir/art/filtered_func_clean_tSNR.nii.gz 2>&1 1>/dev/null | tee -a $log
+    $featdir/art/filtered_func_tSNR.nii.gz 2>&1 1>/dev/null | tee -a $log
   # Make images.
   for imgtype in tSD tSNR; do
-    slicer $featdir/art/filtered_func_clean_$imgtype.nii.gz -S 2 720 \
-      $featdir/art/filtered_func_clean_$imgtype.png 2>&1 1>/dev/null | tee -a $log
+    slicer $featdir/art/filtered_func_$imgtype.nii.gz -S 2 720 \
+      $featdir/art/filtered_func_$imgtype.png 2>&1 1>/dev/null | tee -a $log
   done
 
   echo "(id=$id) Saving animated data gifs..." | tee -a $log
   # Save animated gifs of preprocessed and raw func data (each takes ~1.5min)
-  make_data_gif $input $featdir/raw_func.gif
-  make_data_gif $cleanfunc $featdir/filtered_func_clean.gif
+  make_data_gif $input $featdir/raw_func_data.gif
+  make_data_gif $cleanfunc $featdir/filtered_func_data_clean.gif
 fi
 (( $stpstage == 5 )) && cleanup
 
@@ -925,6 +947,33 @@ if (( $ststage <= 6 )); then
       command_check "$hemi data smoothing"
     done
   fi
+fi
+(( $stpstage == 6 )) && cleanup
+
+## STAGE 7
+## Generating QA report
+if (( $ststage <= 7 )); then
+  # Evaluating surface data coverage
+  echo "(id=$id) Evaluating surface coverage..." | tee -a $log
+  lobes="FRONTAL TEMPORAL OCCIPITAL PARIETAL"
+  lobedir=$downsampdir/label/PALS_B12_Lobes/masks
+  cover_report=$featdir/surf_coverage.csv
+  echo "Lobe,Hemi,Coverage" > $cover_report
+  for lobe in $lobes; do
+    for hemi in lh rh; do
+      lobe_mask=$lobedir/$hemi.LOBE.$lobe.shape.gii
+      data_mask=$featdir/$hemi.32k_fs_LR.mask.shape.gii
+      lobe_size=$(wb_command -metric-vertex-sum $lobe_mask)
+      command_check "$lobe $hemi coverage"
+      lobe_cover=$(wb_command -metric-vertex-sum $data_mask -roi $lobe_mask)
+      command_check "$lobe $hemi coverage"
+      lobe_cover=$(echo "($lobe_cover / $lobe_size)" | bc -l)
+      echo "$lobe,$hemi,$lobe_cover" >> $cover_report
+    done
+  done
+
+  echo "(id=$id) Generating QA report..." | tee -a $log
+  python $NPDL_SCRIPT_DIR/lib/make_preproc_QA_report.py $featdir
 fi
 
 cleanup
